### ISSUE TITLE
Error Retrieving Connections From Config File: Missing CRMDeveloperExtensions.config file

### ISSUE THREAD

**Issue by punyargybargy** [jlattimer/CRMDeveloperExtensions#21]
This error shows up if the config file is checked in in TFS.
Even if the file is write protected, it still should be possible to read the contents of the file.

If you need any other information, please let me know.

Best Regards

**Comment by jlattimer** [comment]
Can you provide additional detail as I'm not able to repro.
I've checked in CRMDeveloperExtensions.config to TFS and that alone doesn't throw an error. I've also flagged the file as Read-Only in Windows but it doesn't effect anything either. 

What I will probably end up doing is a combination of checking if the file is read-only or not and if the data has changed and then prompting to check out the file first if required. In some instances updating the file is required to track which CRM connection is selected in order to use some of the right-click content menu publish functionality.

**Comment by jlattimer** [comment]
I've minimized the amount of writes back to the config file but writing to it will still be required so I've opted to automatically make the file editable so it shouldn't throw any errors.
