### ISSUE TITLE
CommonResources Not Testable

### ISSUE THREAD

**Issue by mike9182** [jlattimer/CRMDeveloperExtensions#27]
I would like to refactor the connection pane to use MVVM and eventually the other windows as well. I see this as the first step to making them testable.

What are your thoughts?

**Comment by jlattimer** [comment]
I'm hoping to get a new release out next few days with the new functionality and changes thus far. Once that's out I'm probably going to work on a different project for a bit that needs updating for CRM 2016 - so that would probably be a good time to start on something like this in case there are lots of changes. Merging will be easier with only 1 person making updates. 

And thanks again for contributing!
