### ISSUE TITLE
MappedTo should have possibility of typing custom path

### ISSUE THREAD

**Issue by LeszekSzejka** [jlattimer/CRMDeveloperExtensions#3]
If solution contains custom folders and subfolders you can not correctly map existing server resource with local file thereupon you can not compare these two files

**Comment by eborn** [comment]
This problem also affects Javascript bundles, which are currently quite commonly used for CRM scripting due to async loading of scripts. They don't appear in the dialog. See the screenshot for reference, these files will not be displayed in the dialog.
![image](https://cloud.githubusercontent.com/assets/3460822/9409056/c8bd5bf0-4817-11e5-85ff-bdfaf7e0c3eb.png)

**Comment by jlattimer** [comment]
Good to know. For the next release I had fixed the issue where minified files appeared under the base version. I think I just need to extended that a little to look for this scenario also.

**Comment by jlattimer** [comment]
v1.2.0.0 you should be able to get files nested under other files in cases where they've been minified or bundled.
