### ISSUE TITLE
Publish to CRM shortcut key

### ISSUE THREAD

**Issue by LeszekSzejka** [jlattimer/CRMDeveloperExtensions#31]
Usefull feature will be a VS command (or extension global option) for which user can bind shortuct-key accessible from eg. text editor.

**Comment by jlattimer** [comment]
Actually as it turns out you can already do this. 

Tools -> Options -> Environment -> Keyboard

From there you can access the various menu items that are already set up. In this example, I targeted the context menu to publish a web resource when right clicking inside the code file

![image](https://cloud.githubusercontent.com/assets/1769982/20642921/70efdeac-b3e1-11e6-97ae-9176e7eebd0c.png)
